* About 
  - roam is a plugin that reimplements [[https://www.orgroam.com/][org-roam]] in neovim by using the same database model.
    so you can easily switch between org-roam in emacs and roam  in neovim.

  - It depends on the great [[https://github.com/nvim-orgmode/orgmode][orgmode]] plugin by [[https://github.com/kristijanhusak][Kristijan Husak]]
* Status
    This are the very early stages of the plugin, so expect bugs and missing features.
    I dont yet have a proper readme as you can see bellow.

* Install 

* How to use
  Roam by default will use your existing org-roam database from emacs located at =~/.config/emacs/.local/cache/org-roam.db=.
  If you want to use a different database you can set this in your ~init.lua~ file like this:
    #+BEGIN_SRC lua
    require('roam').setup {
      database = "/path/to/your/org-roam.db"
    }
    #+END_SRC

** Commands
   Roam exposes only two commands for now:
    - ~RoamSearch~ : This will open a telescope window with the search results
    - ~RoamOpenId~ : This will open the file with the id under the cursor

** Keybindings
    You can set your own keybindings like this:
    #+BEGIN_SRC lua
    vim.api.nvim_set_keymap('n', '<leader>rs', '<cmd>RoamSearch<CR>', { noremap = true, silent = true })
    vim.api.nvim_set_keymap('n', '<leader>ro', '<cmd>RoamOpenId<CR>', { noremap = true, silent = true })
    #+END_SRC

* Progress
    - [X] Implement the search
    - [X] Create vim commands for search and GoTo link
    - [X] Insert link under cursor (~C-k~ in telescope does this now)
    - [X] Fix the goto links

    - [ ] Register new file in Roam
          - We should be able to get the info from the OrgApi
          - set and Id property or read the id if it already exists
          - save/update this id in the roam db
          - Create new roam document with the title under the cursor (it should popup a prompt to choose which template to use)

    - [ ] Purge/Sync database
          - Purge should cleanup the whole database
          - Sync should go through every file in the roam folder and update the database
          - It should also create ids,titles for files that do not have these properties
